# fly.toml app configuration file generated for boootx on 2023-11-03T12:27:40+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "boootx"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile_fly"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
