name: wakeup

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run wakeup script
        run: python wakeup.py
        env:
          BING_AUTH_TOKEN: ${{ secrets.BING_AUTH_TOKEN }}
          BING_AUTH_TOKEN_KIEV: ${{ secrets.BING_AUTH_TOKEN_KIEV }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          CITY: ${{ secrets.CITY }}